[platformio]
src_dir = .
include_dir = .
default_envs = cm4, cm7

[env:cm7]
platform = ststm32
board = stm32h747bi_cm7
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
board_build.ldscript = Makefile/CM7/stm32h747xx_flash_CM7.ld
extra_scripts =
    pre:scripts/build_script.py
    pre:tools/generate_fonts.py
build_flags =
    -std=gnu23
    -DCORE_CM7
    -DUSE_HAL_DRIVER
    -DSTM32H747xx
    -DUSE_PWR_LDO_SUPPLY
    -ICM7/Core/Inc
    -ICM7/Core/Inc/steering
    -ICM7/Core/Inc/steering/drivers
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    -isystem Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -isystem Drivers/CMSIS/Include
    -isystem Utilities/JPEG
    -ICM7/FATFS/Target
    -ICM7/FATFS/App
    -isystem Middlewares/Third_Party/FatFs/src
    -ICommon/Inc
    -ICommon/Inc/steering
    -Itools/generated
build_src_filter =
    +<CM7/Core/Src/>
    +<Drivers/STM32H7xx_HAL_Driver/Src>
    -<Drivers/STM32H7xx_HAL_Driver/Src/*_template.c>
    +<Common/Src/>
    +<Makefile/CM7/*.s>
    +<Utilities/JPEG/>
    -<Utilities/JPEG/*_template.c>
    +<CM7/FATFS/Target/>
    +<CM7/FATFS/App/>
    +<Middlewares/Third_Party/FatFs/src/>
    +<Middlewares/Third_Party/FatFs/src/option/syscall.c>
    +<tools/generated/*.c>
    -<Middlewares/Third_Party/FatFs/src/option/cc*.c>
    -<CM4/**>
    -<Makefile/CM4/**>
lib_deps = 
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libraster-sw.git#v2.1.0

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<CM7/Core/Src/steering>
    +<CM7/Core/Inc/steering>

[env:cm4]
platform = ststm32
board = stm32h747bi_cm4
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
board_build.ldscript = Makefile/CM4/stm32h747xx_flash_CM4.ld
extra_scripts = pre:scripts/build_script.py
build_flags =
    -std=gnu23
    -DCORE_CM4
    -DUSE_HAL_DRIVER
    -DSTM32H747xx
    -DUSE_PWR_LDO_SUPPLY
    -ICM4/Core/Inc
    -ICM4/Core/Inc/steering
    -ICM4/Core/Inc/steering/drivers
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    -isystem Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -isystem Drivers/CMSIS/Include
    -ICommon/Inc
    -ICommon/Inc/steering
build_src_filter =
    +<CM4/Core/Src/>
    +<Drivers/STM32H7xx_HAL_Driver/Src>
    -<Drivers/STM32H7xx_HAL_Driver/Src/*_template.c>
    +<Common/Src/>
    +<Makefile/CM4/*.s>
    -<CM7/**>
    -<Makefile/CM7/**>
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0


check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<CM4/Core/Src/steering>
    +<CM4/Core/Inc/steering>

[env:tests_cm7]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu23
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
    -ICM7/Core/Inc/steering
    -ICommon/Inc/steering
    -Itools/generated
    -Itest/include
build_src_filter =
    +<CM7/Core/Src/steering>
    +<tools/generated/*.c>
    +<Common/Src/steering>
test_filter = cm7/*
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libraster-sw.git#v2.1.0

[env:tests_cm4]
platform = native
test_framework = unity
test_build_src = true
build_flags = 
    -std=gnu23
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
    -ICM4/Core/Inc/steering
    -ICM4/Core/Inc/steering/drivers
    -ICommon/Inc/steering
    -Itest/include
build_src_filter =
    +<CM4/Core/Src/steering>
    +<Common/Src/steering>
test_filter = cm4/*
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0

[env:tests_common]
platform = native
test_framework = unity
test_build_src = true
build_flags = 
    -std=gnu23
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
    -ICommon/Inc/steering
    -Itest/include
build_src_filter =
    +<Common/Src/steering>
test_filter = common/*
lib_deps = https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

[env:bootloader]
platform = ststm32
board = disco_h747xi
upload_protocol = stlink
debug_tool = stlink
platform_packages =
    toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
board_build.ldscript = steering-wheel-bootloader-sw/Makefile/CM7/stm32h747xx_flash_CM7.ld
board_upload.maximum_ram_size = 1048576
extra_scripts = pre:steering-wheel-bootloader-sw/tools/generate_fonts.py
build_flags =
    -std=gnu23
    -DCORE_CM7
    -DUSE_HAL_DRIVER
    -DUSE_FULL_LL_DRIVER
    -DSTM32H747xx
    -DUSE_PWR_LDO_SUPPLY
    -DUSE_PWR_DIRECT_SMPS_SUPPLY
    -Isteering-wheel-bootloader-sw/CM7/Core/Inc
    -Isteering-wheel-bootloader-sw/Common/Inc
    -Isteering-wheel-bootloader-sw/Drivers/STM32H7xx_HAL_Driver/Inc
    -Isteering-wheel-bootloader-sw/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    -Isteering-wheel-bootloader-sw/Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -Isteering-wheel-bootloader-sw/Drivers/CMSIS/Include
    -Isteering-wheel-bootloader-sw/Utilities/JPEG
    -Isteering-wheel-bootloader-sw/CM7/FATFS/Target
    -Isteering-wheel-bootloader-sw/CM7/FATFS/App
    -Isteering-wheel-bootloader-sw/Middlewares/Third_Party/FatFs/src
    -Isteering-wheel-bootloader-sw/tools/generated
build_src_filter =
    +<steering-wheel-bootloader-sw/CM7/Core/Src/>
    +<steering-wheel-bootloader-sw/Drivers/STM32H7xx_HAL_Driver/Src/>
    -<steering-wheel-bootloader-sw/Drivers/STM32H7xx_HAL_Driver/Src/*_template.c>
    +<steering-wheel-bootloader-sw/Common/Src/>
    +<steering-wheel-bootloader-sw/Makefile/CM7/*.s>
    +<steering-wheel-bootloader-sw/Utilities/JPEG/>
    -<steering-wheel-bootloader-sw/Utilities/JPEG/*_template.c>
    +<steering-wheel-bootloader-sw/CM7/FATFS/Target/>
    +<steering-wheel-bootloader-sw/CM7/FATFS/App/>
    +<steering-wheel-bootloader-sw/Middlewares/Third_Party/FatFs/src/>
    +<steering-wheel-bootloader-sw/Middlewares/Third_Party/FatFs/src/option/syscall.c>
    +<steering-wheel-bootloader-sw/tools/generated/*.c>
    -<steering-wheel-bootloader-sw/Middlewares/Third_Party/FatFs/src/option/cc*.c>
    -<CM4/**>
    -<Makefile/CM4/**>
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libraster-sw.git#v2.1.0

[env:simulator]
platform = native
extra_scripts =
    pre:tools/generate_fonts.py
    pre:simulator/link_flags.py
build_flags =
    -std=gnu23
    -ICM7/Core/Inc/steering
    -ICM4/Core/Inc/steering
    -ICM4/Core/Inc/steering/drivers
    -ICommon/Inc/steering
    -Itools/generated
    -Isimulator/include
build_src_filter =
    +<CM7/Core/Src/steering>
    +<CM4/Core/Src/steering/inputs-api.c>
    +<CM4/Core/Src/steering/parameters-api.c>
    +<CM4/Core/Src/steering/leds-api.c>
    +<CM4/Core/Src/steering/can-communications-*.c>
    +<CM4/Core/Src/steering/drivers/ws2812b-api.c>
    +<tools/generated/*.c>
    +<Common/Src/steering>
    +<simulator/src/*.c>
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libraster-sw.git#v2.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0
