#include "micron-steer-sdram.h"

typedef void (*micron_steer_sdram_api_delay_callback)(uint32_t);

typedef enum MicronSteerSdramReturnCode (*micron_steer_sdram_api_send_command_callback)(struct MicronSteerSdramCommand *cmd);

typedef enum MicronSteerSdramReturnCode (*micron_steer_sdram_api_program_refresh_rate_callback)(uint32_t refresh_rate);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_init(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_delay_callback delay_func, micron_steer_sdram_api_send_command_callback send_cmd_func, micron_steer_sdram_api_program_refresh_rate_callback program_refresh_rate_func);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_clock_enable(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_precharge(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_mode_reg_config(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_refresh_mode(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_refresh_rate(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_program_refresh_rate_callback program_refresh_rate_func);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_enter_power_mode(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);

enum MicronSteerSdramReturnCode micron_steer_sdram_api_exit_power_mode(struct MicronSteerSdramContext *ctx, micron_steer_sdram_api_send_command_callback send_command_callback);
