name: PlatformIO Project CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on:
      group: ci-runners
      labels: Linux
    continue-on-error: ${{ !(github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Generator Dependencies
        run: pip install Pillow numpy scipy jinja2

      - name: Build CM7
        run: pio run -e cm7

      - name: Build CM4
        run: pio run -e cm4

      - name: Build bootloader
        run: pio run -e bootloader
      
      - name: Run Unit Tests
        run: pio test -e tests_cm4 -e tests_cm7 -e tests_common

      - name: Static Code Analysis
        if: github.ref == 'refs/heads/dev'
        run: |
          pio check -e cm4 -e cm7 || true
